import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import "./globals.css";
import Responsive from "./components/Nav/Responsive";
import Footer from "./components/Footer/Footer";
import Reduxprovider from "./Redux/provider";
import toast, { Toaster } from 'react-hot-toast';

const barlow_Condensed = Barlow_Condensed({
  weight:['300','400','400','500','600','700','800'],
  subsets:['latin']
})

export const metadata: Metadata = {
  title: "BurgerByte | Food",
  description: "Generated by create next app",
 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Reduxprovider>
    <html lang="en">
      <head>
          <link rel="icon" href="/images/burger_byte_logo.png" />
      </head>
      <body className={barlow_Condensed.className}>
          <Responsive/>
          {children}
          <Footer/>
          {/* <ToastContainer /> */}
          <Toaster />

      </body>
    </html>
    </Reduxprovider>
  );
}
